In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("Data/data.csv")
data.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [4]:
print(f"There are {data.shape[0]} Rows and {data.shape[1]} Columns")

There are 4238 Rows and 16 Columns

In [41]:
print(f"Number of duplicates {data.duplicated().sum()}")

Number of duplicates 0

In [7]:
data.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [42]:
data.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,4238.000000,4238.000000,4133.000000,4238.000000,4209.000000,4185.000000,4238.000000,4238.000000,4238.000000,4188.000000,4238.000000,4238.000000,4219.000000,4237.000000,3850.000000,4238.000000
mean,0.429212,49.584946,1.978950,0.494101,9.003089,0.029630,0.005899,0.310524,0.025720,236.721585,132.352407,82.893464,25.802008,75.878924,81.966753,0.151958
std,0.495022,8.572160,1.019791,0.500024,11.920094,0.169584,0.076587,0.462763,0.158316,44.590334,22.038097,11.910850,4.080111,12.026596,23.959998,0.359023
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.070000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.400000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,144.000000,89.875000,28.040000,83.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,696.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [43]:
data.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.028979,0.017352,0.197596,0.317930,-0.052506,-0.004546,0.005313,0.015708,-0.070322,-0.035989,0.057933,0.081672,-0.116620,0.006083,0.088428
age,-0.028979,1.000000,-0.165883,-0.213748,-0.192791,0.122995,0.057655,0.307194,0.101258,0.262131,0.394302,0.206104,0.135800,-0.012823,0.122256,0.225256
education,0.017352,-0.165883,1.000000,0.018532,0.008085,-0.010815,-0.035112,-0.081970,-0.038680,-0.023115,-0.129631,-0.062316,-0.137504,-0.054206,-0.035721,-0.054059
currentSmoker,0.197596,-0.213748,0.018532,1.000000,0.769690,-0.048938,-0.032988,-0.103260,-0.044295,-0.046562,-0.130230,-0.107746,-0.167650,0.062356,-0.056826,0.019456
cigsPerDay,0.317930,-0.192791,0.008085,0.769690,1.000000,-0.046134,-0.032707,-0.066146,-0.037067,-0.026320,-0.088780,-0.056632,-0.092856,0.075157,-0.058960,0.057884
BPMeds,-0.052506,0.122995,-0.010815,-0.048938,-0.046134,1.000000,0.117365,0.261187,0.052047,0.080558,0.254219,0.194227,0.100668,0.015233,0.051176,0.087489
prevalentStroke,-0.004546,0.057655,-0.035112,-0.032988,-0.032707,0.117365,1.000000,0.074830,0.006949,0.000067,0.057009,0.045190,0.025891,-0.017676,0.018431,0.061810
prevalentHyp,0.005313,0.307194,-0.081970,-0.103260,-0.066146,0.261187,0.074830,1.000000,0.077808,0.163993,0.696755,0.615751,0.301318,0.147261,0.086834,0.177603
diabetes,0.015708,0.101258,-0.038680,-0.044295,-0.037067,0.052047,0.006949,0.077808,1.000000,0.040278,0.111283,0.050329,0.087036,0.048994,0.617627,0.097317
totChol,-0.070322,0.262131,-0.023115,-0.046562,-0.026320,0.080558,0.000067,0.163993,0.040278,1.000000,0.208908,0.165182,0.115767,0.091125,0.046408,0.082184
sysBP,-0.035989,0.394302,-0.129631,-0.130230,-0.088780,0.254219,0.057009,0.696755,0.111283,0.208908,1.000000,0.784002,0.326981,0.182246,0.140621,0.216429
diaBP,0.057933,0.206104,-0.062316,-0.107746,-0.056632,0.194227,0.045190,0.615751,0.050329,0.165182,0.784002,1.000000,0.377588,0.181255,0.061231,0.145299
BMI,0.081672,0.135800,-0.137504,-0.167650,-0.092856,0.100668,0.025891,0.301318,0.087036,0.115767,0.326981,0.377588,1.000000,0.067678,0.087377,0.075192
heartRate,-0.116620,-0.012823,-0.054206,0.062356,0.075157,0.015233,-0.017676,0.147261,0.048994,0.091125,0.182246,0.181255,0.067678,1.000000,0.094500,0.022913
glucose,0.006083,0.122256,-0.035721,-0.056826,-0.058960,0.051176,0.018431,0.086834,0.617627,0.046408,0.140621,0.061231,0.087377,0.094500,1.000000,0.125544
TenYearCHD,0.088428,0.225256,-0.054059,0.019456,0.057884,0.087489,0.061810,0.177603,0.097317,0.082184,0.216429,0.145299,0.075192,0.022913,0.125544,1.000000

### Detected Problems

* Nulls Values

In [30]:
def col_details(col_name):
    
    print(f"####### {col_name} ########")
    
    print(f"\nNumber of unique Values {data[col_name].nunique()}")
    
    print(f"There are {data[col_name].isnull().sum()} Null Values")
    random_number = np.random.randint(4000)
    print(f"\nSome Random Data \n {data[col_name][random_number:random_number + 5].values}")
    print(f"\nTop 5 Values {data[col_name].value_counts().index[:5]}")
    
    print(f"Max value is {data[col_name].max()} Min {data[col_name].min()}")

### Male

In [31]:
col_details("male")

####### male ########

Number of unique Values 2
There are 0 Null Values

Some Random Data
 [0 1 1 1 1]

Top 5 Values Int64Index([0, 1], dtype='int64')
Max value is 1 Min 0

### age

In [32]:
col_details("age")

####### age ########

Number of unique Values 39
There are 0 Null Values

Some Random Data
 [46 62 35 49 49]

Top 5 Values Int64Index([40, 46, 42, 41, 48], dtype='int64')
Max value is 70 Min 32

### education
* Null values : there are many ways to handle null values such as replacing them with Medain or Mean or using some algorthim for numerical data

In [33]:
col_details("education")

####### education ########

Number of unique Values 4
There are 105 Null Values

Some Random Data
 [3. 4. 2. 3. 1.]

Top 5 Values Float64Index([1.0, 2.0, 3.0, 4.0], dtype='float64')
Max value is 4.0 Min 1.0

In [39]:
print(f"{data['education'].isnull().sum() / len(data) * 100 } %")

2.4775837659273243 %

In [51]:
# let's handle null values using medain
# K-Nearest-Neighbours

data[data["education"].isnull()] = data['education'].median()

In [53]:
data["education"].isnull().sum()

0